Do not expect 0 values in cacher_test
Remaining failure:

--- FAIL: TestCacherGetMetrics (0.00s)
    cacher_test.go:75:
                Error Trace:    cacher_test.go:75
                Error:          Not equal:
                                expected: "http_outgoing_requests_total{code=\"200\",method=\"get\",recipient=\"cacher\"} 2\n"
                                actual  : "http_outgoing_requests_total{code=\"200\",method=\"get\",recipient=\"cacher\"} 1\n"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,2 +1,2 @@
                                -http_outgoing_requests_total{code="200",method="get",recipient="cacher"} 2
                                +http_outgoing_requests_total{code="200",method="get",recipient="cacher"} 1

                Test:           TestCacherGetMetrics